# Generated by Django 3.2.5 on 2023-02-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('visite', 'Visite'), ('suivi', 'Suivi'), ('operation', 'Operation')], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='secretariat.patient')),
            ],
        ),
    ]
