# Generated by Django 3.2.5 on 2023-02-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0002_consultation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='adress',
            new_name='address',
        ),
    ]
