# Generated by Django 3.2.5 on 2023-02-12 16:16

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0003_rename_adress_patient_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=500)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
